name: cash_io
description: "Cash Input/Output"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  material_symbols_icons: ^4.2709.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - licenses/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/nunito/Nunito-VariableFont_wght.ttf
        - asset: fonts/nunito/Nunito-Italic-VariableFont_wght.ttf
          style: italic
